### ISSUE TITLE
User creation through scim api

### ISSUE THREAD

**Issue by anogues** [crflynn/databricks-api#12]
Hello

I forked your project and added the following to be able to create new users through the api.

https://docs.databricks.com/dev-tools/api/latest/scim/scim-users.html

    def create_user(self, user_name=None, headers=None):
        _data = {}
        if user_name is not None:
            _data['schemas'] = ["urn:ietf:params:scim:schemas:core:2.0:User"]
            _data['userName'] = user_name
            _data['entitlements'] = [{'value': 'allow-cluster-create'}]		
        return self.client.perform_query('POST', '/preview/scim/v2/Users', data=_data, headers=headers)

Of course it can be improved to allow to pass groups and so on. Just in case you want it.

**Comment by crflynn** [comment]
It looks like there is some work being done on the cli package for adding SCIM: https://github.com/databricks/databricks-cli/pull/311. I don't plan on supporting anything outside of what's available from the cli package at the moment. I imagine this will be officially supported eventually and then available here subsequently.
