### ISSUE TITLE
Cannot use DatabricksAPI.workspace

### ISSUE THREAD

**Issue by MaxCaudle** [crflynn/databricks-api#17]
According to the documentation I think I should be able to `from databricks_api import DatabricksAPI` and then access the `DatabricksAPI.workspace`, but this doesnt seem to be working. My main goal is to check if a directory structure exists, and if not create one.

```
In [1]: from databricks_api import DatabricksAPI

In [2]: DatabricksAPI.workspace.list()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-09fa92501b4f> in <module>
----> 1 DatabricksAPI.workspace.list()

AttributeError: type object 'DatabricksAPI' has no attribute 'workspace'

In [3]: DatabricksAPI.workspaces
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-12099cc2227b> in <module>
----> 1 DatabricksAPI.workspaces

AttributeError: type object 'DatabricksAPI' has no attribute 'workspaces'
```

It looks like the DatabricksAPI object doesn't have any publicly accessible attrs:
```
DatabricksAPI.__dict__

mappingproxy({'__module__': 'databricks_api.databricks',
              '__init__': <function databricks_api.databricks.DatabricksAPI.__init__(self, **kwargs)>,
              '__dict__': <attribute '__dict__' of 'DatabricksAPI' objects>,
              '__weakref__': <attribute '__weakref__' of 'DatabricksAPI' objects>,
              '__doc__': None})
```

**Comment by crflynn** [comment]
You just need to instantiate the api first:

```python
from databricks_api import DatabricksAPI

# Provide a host and token
db = DatabricksAPI(
    host="example.cloud.databricks.com",
    token="dpapi123..."
)

# OR a host and user and password
db = DatabricksAPI(
    host="example.cloud.databricks.com",
    user="me@example.com",
    password="password"
)
```

The api attributes like `workspace` are created dynamically [_on instantiation_](https://github.com/crflynn/databricks-api/blob/5c2e6d5a693cfff8fca512abc8a39fd4571fe886/databricks_api/databricks.py#L29), so you can't access them on the class. Once you have an instance of DatabricksAPI you should be able to access the api components like this:

```python
db.workspace.list(path="whatever")
```

**Comment by MaxCaudle** [comment]
Ah ok, the docs make it look like you access it off an un instantiated instance of the class. Thanks for the clarification!

**Comment by crflynn** [comment]
Ah I can try to update them to use the instance rather than the class. Good feedback, thanks.

**Comment by MaxCaudle** [comment]
I can make a PR to update the readme if you'd prefer?

**Comment by crflynn** [comment]
Sure. Should just be this line, I believe, as well as running it to update the README
https://github.com/crflynn/databricks-api/blob/5c2e6d5a693cfff8fca512abc8a39fd4571fe886/generate_docs.py#L94

**Comment by MaxCaudle** [comment]
PR created, my databricks-cli version is 2 patches ahead of yours, so the README has some new functions included.

**Comment by crflynn** [comment]
Ah I've been reluctant to update the cli version because the maintainers have broken the init_scripts arg in parts of the API. It's [happened before](https://github.com/crflynn/databricks-api/issues/6) and i didn't want to break anyone's use of it by upgrading yet. Here is the current issue for reference: https://github.com/databricks/databricks-cli/issues/335

**Comment by MaxCaudle** [comment]
Ok, rolled my version back. Just changed `DatabricksAPI` -> `db`.

Closing issue
