### ISSUE TITLE
Add Support for Azure and GCP

### ISSUE THREAD

**Issue by hriebesehl** [crflynn/databricks-api#24]
Currently methods `db.cluster.create_cluster()`, `db.cluster.edit_cluster()`, `db.instance_pool.create_instance_pool()`, and `db.instance_pool.edit_instance_pool()` only support API calls to AWS-based databricks workspaces. I'd recommend adding `azure_attributes` and `gcp_attributes` as parameters to these functions to support API calls on all platforms.

edit: opened an issue on databricks-cli [here](https://github.com/databricks/databricks-cli/issues/408)

**Comment by crflynn** [comment]
This package just wraps databricks-cli; you might be better off requesting there.

**Comment by hriebesehl** [comment]
Apologies - will do.
