### ISSUE TITLE
db.jobs.list_runs returns a different amount of runs than limit specified

### ISSUE THREAD

**Issue by SqrtPapere** [crflynn/databricks-api#25]
Hi, 

I am having issues with the method `db.jobs.list_runs` because it seems that the `limit` parameter isn't used and the number of runs returned always differs from `limit`.

For example:

`len(db.jobs.list_runs(limit=25)['runs'])
`

returns **21** elements instead of the **25** expected.

**Comment by crflynn** [comment]
This package is just a thin wrapper around https://github.com/databricks/databricks-cli, which might be a more appropriate location for this issue.
