### ISSUE TITLE
how do you do multitask 

### ISSUE THREAD

**Issue by hardiktalati** [crflynn/databricks-api#26]
Does the library support jobs api 2.1 as we want to try out multi task using this library.

**Comment by crflynn** [comment]
This just wraps the cli package, so whatever the cli supports should be supported here. According to [this issue in the cli repo](https://github.com/databricks/databricks-cli/issues/405) it looks like the answer to your question is no.

**Comment by hardiktalati** [comment]
Thanks buddy. Let me chat with databricks folks on it.

**Comment by nordp** [comment]
Hi @hardiktalati ,

The following PR attempts to address this issue in `databricks-cli`:
https://github.com/databricks/databricks-cli/pull/434. Please help try it out and let me know if it doesn't work for you.
