### ISSUE TITLE
Support for Azure-Databricks

### ISSUE THREAD

**Issue by aidin-zadeh** [crflynn/databricks-api#27]
Is there any timeline to support Azure-Databricks API?

**Comment by crflynn** [comment]
Does it not work with a host + token ?

**Comment by jbdekker** [comment]
Works for 90%, but 'azure_attributes' is not supported by create_cluster() for example

**Comment by crflynn** [comment]
Refer to: https://github.com/databricks/databricks-cli/issues/408

**Comment by crflynn** [comment]
https://github.com/crflynn/databricks-api/issues/24

**Comment by aidin-zadeh** [comment]
I was using Azure databricks personal access token which turned out not to have rights to the rest API within our current setup. Switching to Azure active directory token resolved the issue for me. Thanks for response.
