### ISSUE TITLE
New git_source parameter not in API

### ISSUE THREAD

**Issue by tomshaffner** [crflynn/databricks-api#29]
The JobsCreate portion of the API now has a [`git_source` parameter](https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate) in the 2.1 API. When I try to use this however, I get the following error:

`TypeError: create_job() got an unexpected keyword argument 'git_source'`

I'm assuming this means the parameters need to be rescanned in a new update of the package; is there a plan to do this any time soon?

**Comment by crflynn** [comment]
This is an issue with the cli project. Here is a related PR: https://github.com/databricks/databricks-cli/pull/490
