### ISSUE TITLE
Add tasks to an existing job

### ISSUE THREAD

**Issue by asafeunico** [crflynn/databricks-api#35]
Hello guys, I'm implementing this Lib as an interface in the manipulations, but I couldn't understand how I'm going to add a new task to an existing job.
How could I do this?

**Example**:

There is the method
```
db.jobs.reset_job(
    "job_id",
    new_settings,
) 
```

and I need something like:

```
db.jobs.update_job(
    "job_id",
    new_settings,
) 
```

**Comment by crflynn** [comment]
maybe something like this?

```python
job = db.jobs.get_job("job_id")
new_settings = modify_settings(job["settings"])
db.jobs.reset_job("job_id", new_settings)
```

**Comment by asafeunico** [comment]
@crflynn , yes man.
It will work for what I need.
Thksss
