### ISSUE TITLE
init_script support in creating cluster

### ISSUE THREAD

**Issue by amor-volastra** [crflynn/databricks-api#39]
Hello, 
Thanks for providing this nice wrapper. 
I was wondering if there is anyway to set 'init_scripts' parameter in db.cluster.create_cluster command. (which exists in official website for Cluster API 2.0 here: https://docs.databricks.com/dev-tools/api/latest/clusters.html)

Thanks,

**Comment by crflynn** [comment]
This is an upstream issue: https://github.com/databricks/databricks-cli/issues/335
