### ISSUE TITLE
Create Cluster init_script

### ISSUE THREAD

**Issue by chaene82** [crflynn/databricks-api#6]
Hi

I like your API very much and I will use it in my CI pipeline. Unfortunately I have a problem adding my init_script to the cluster.

This is my code:

    cluster_json = db.cluster.create_cluster(
       num_workers=2,
       cluster_name="az-ckw-uieb-databricks-devops_test",
       spark_version="5.5.x-scala2.11",
       spark_conf=None,
       node_type_id="Standard_DS3_v2",
       spark_env_vars={
           "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
       },
       autotermination_minutes=120,
       enable_elastic_disk=True,
       init_scripts=[{'dbfs': {'destination': 'dbfs:/databricks/scripts/oracle-install.sh'}}],
    )

However, if I execute it, I got this error message:

TypeError: create_cluster() got an unexpected keyword argument 'init_scripts'

Any idea?

Many Thanks
Christoph

**Comment by crflynn** [comment]
According to this [issue](https://github.com/databricks/databricks-cli/issues/264), the `init_scripts` parameter on the create cluster endpoint is not currently supported by the `databricks-cli` package. The `databricks-api` package relies directly upon the `databricks-cli` package to autogenerate the API client, so it will need to be added to the cli package and released before it can be supported here directly.

**Comment by crflynn** [comment]
It looks like there is an open [PR](https://github.com/databricks/databricks-cli/pull/266) which adds that parameter back to the client.

**Comment by crflynn** [comment]
Looks like it was merged so the next release of the cli package should resolve this.

**Comment by crflynn** [comment]
fixed in [0.4.0](https://pypi.org/project/databricks-api/0.4.0/)
